// place files you want to import through the `$lib` alias in this folder.
export const languageMap: Record<App.TechStack, string> = {
    astro: 'Astro',
    chakra: 'Chakra',
    bootstrap: 'Bootstrap',
    wasm: 'WebAssembly',
    'c#': 'C#',
    dart: 'Dart',
    express: 'Express',
    go: 'Go',
    java: 'Java',
    js: 'JavaScript',
    "jsdoc-typed": 'JSDoc Typed',
    kt: 'Kotlin',
    mongo: 'MongoDB',
    nixpack: 'Nixpacks',
    nuxt: 'Nuxt',
    pgsql: 'PostgreSQL',
    py: 'Python',
    redis: 'Redis',
    remix: 'Remix',
    rust: 'Rust',
    svelte: 'Svelte',
    tailwind: 'Tailwind',
    ts: 'TypeScript',
    vue: 'Vue',
    radix: 'Radix UI',
    daisy: 'Daisy UI',
    unifiedjs: 'Unified JS',
    vercel: 'Vercel',
    jupyter: 'Jupyter Notebook',
    railway: 'Railway',
    vite: 'Vite',
    node: 'Node.js',
    react: 'React',
    next: 'Next.js',
    docker: 'Docker',
    dotnet: '.NET',
}