image: node

before_script:
  - yarn 

cache:
  paths:
    - node_modules/

pages:
  script:
    - yarn run build
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
